// === hopefully an exhaustive list of property groups ===
export const propertyGroups: Record<string, string[]> = {
  padding: [
    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
  ],
  margin: [
    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
  ],
  border: [
    'border',
    'border-width',
    'border-style',
    'border-color',
    'border-top',
    'border-right',
    'border-bottom',
    'border-left',
    'border-top-width',
    'border-right-width',
    'border-bottom-width',
    'border-left-width',
    'border-top-style',
    'border-right-style',
    'border-bottom-style',
    'border-left-style',
    'border-top-color',
    'border-right-color',
    'border-bottom-color',
    'border-left-color',
    'border-radius',
    'border-top-left-radius',
    'border-top-right-radius',
    'border-bottom-right-radius',
    'border-bottom-left-radius',
    'border-image',
    'border-image-source',
    'border-image-slice',
    'border-image-width',
    'border-image-outset',
    'border-image-repeat',
  ],
  outline: [
    'outline',
    'outline-width',
    'outline-style',
    'outline-color',
    'outline-offset',
  ],
  box: ['box-sizing', 'box-shadow', 'box-decoration-break'],

  background: [
    'background',
    'background-color',
    'background-image',
    'background-position',
    'background-size',
    'background-repeat',
    'background-origin',
    'background-clip',
    'background-attachment',
    'background-blend-mode',
  ],

  flex: [
    'display',
    'flex-direction',
    'flex-wrap',
    'flex-flow',
    'justify-content',
    'align-items',
    'align-content',
    'align-self',
    'flex',
    'flex-grow',
    'flex-shrink',
    'flex-basis',
    'order',
  ],

  grid: [
    'display',
    'grid-template-columns',
    'grid-template-rows',
    'grid-template-areas',
    'grid-template',
    'grid-auto-columns',
    'grid-auto-rows',
    'grid-auto-flow',
    'grid',
    'grid-row-start',
    'grid-column-start',
    'grid-row-end',
    'grid-column-end',
    'grid-row',
    'grid-column',
    'grid-area',
    'place-items',
    'place-content',
    'place-self',
    'gap',
    'row-gap',
    'column-gap',
  ],

  position: ['position', 'top', 'right', 'bottom', 'left', 'z-index'],

  size: [
    'width',
    'min-width',
    'max-width',
    'height',
    'min-height',
    'max-height',
    'aspect-ratio',
  ],

  font: [
    'font',
    'font-family',
    'font-size',
    'font-style',
    'font-variant',
    'font-weight',
    'font-size-adjust',
    'font-stretch',
    'font-kerning',
    'font-feature-settings',
    'font-variant-caps',
    'font-variant-ligatures',
    'font-variant-numeric',
    'font-variant-east-asian',
  ],
  text: [
    'color',
    'line-height',
    'letter-spacing',
    'word-spacing',
    'white-space',
    'text-align',
    'text-align-last',
    'text-decoration',
    'text-decoration-color',
    'text-decoration-line',
    'text-decoration-style',
    'text-indent',
    'text-justify',
    'text-overflow',
    'text-shadow',
    'text-transform',
    'text-underline-offset',
    'text-underline-position',
    'direction',
    'unicode-bidi',
    'writing-mode',
    'vertical-align',
  ],

  list: [
    'list-style',
    'list-style-type',
    'list-style-position',
    'list-style-image',
  ],

  table: [
    'border-collapse',
    'border-spacing',
    'caption-side',
    'empty-cells',
    'table-layout',
  ],

  animation: [
    'animation',
    'animation-name',
    'animation-duration',
    'animation-timing-function',
    'animation-delay',
    'animation-iteration-count',
    'animation-direction',
    'animation-fill-mode',
    'animation-play-state',
    '@keyframes',
  ],

  transition: [
    'transition',
    'transition-property',
    'transition-duration',
    'transition-timing-function',
    'transition-delay',
  ],

  transform: [
    'transform',
    'transform-origin',
    'transform-style',
    'perspective',
    'perspective-origin',
    'backface-visibility',
  ],

  filter: ['filter', 'backdrop-filter'],

  visibility: ['visibility', 'opacity', 'overflow', 'overflow-x', 'overflow-y'],

  interactivity: ['cursor', 'pointer-events', 'user-select', 'resize'],

  misc: [
    'box-sizing',
    'content',
    'quotes',
    'counter-reset',
    'counter-increment',
  ],
}
