#!/bin/bash

source ./docker/dev/lib/utils.sh

docker exec \
    -e EXERCISM_DOCKER=true \
    -e EXERCISM_ENV=test \
    -it v3-docker-compose_website_1 \
    /bin/sh \
    '-c' 'bin/rails db:seed'

handle_container_error