export const DEFAULT_BROWSER_STYLES = {
  'a:link': {
    color: '(internal value)',
    textDecoration: 'underline',
    cursor: 'auto',
  },
  'a:visited': {
    color: '(internal value)',
    textDecoration: 'underline',
    cursor: 'auto',
  },
  'a:link:active': { color: '(internal value)' },
  'a:visited:active': { color: '(internal value)' },
  abbr: {},
  address: {
    display: 'block',
    fontStyle: 'italic',
  },
  area: { display: 'none' },
  article: { display: 'block' },
  aside: { display: 'block' },
  audio: {},
  b: { fontWeight: 'bold' },
  base: {},
  bdi: {},
  bdo: { unicodeBidi: 'bidi-override' },
  blockquote: {
    display: 'block',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '40px',
    marginRight: '40px',
  },
  body: {
    display: 'block',
    margin: '8px',
    overflow: 'scroll',
  },
  'body:focus': { outline: 'none' },
  br: {},
  button: {},
  canvas: {},
  caption: {
    display: 'table-caption',
    textAlign: 'center',
  },
  cite: { fontStyle: 'italic' },
  code: { fontFamily: 'monospace' },
  col: { display: 'table-column' },
  colgroup: { display: 'table-column-group' },
  datalist: { display: 'none' },
  dd: {
    display: 'block',
    marginLeft: '40px',
  },
  del: { textDecoration: 'line-through' },
  details: { display: 'block' },
  dfn: { fontStyle: 'italic' },
  dialog: {},
  div: { display: 'block' },
  dl: {
    display: 'block',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '0',
    marginRight: '0',
  },
  dt: { display: 'block' },
  em: { fontStyle: 'italic' },
  'embed:focus': { outline: 'none' },
  fieldset: {
    display: 'block',
    marginLeft: '2px',
    marginRight: '2px',
    paddingTop: '0.35em',
    paddingBottom: '0.625em',
    paddingLeft: '0.75em',
    paddingRight: '0.75em',
    border: '2px groove (internal value)',
  },
  figcaption: { display: 'block' },
  figure: {
    display: 'block',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '40px',
    marginRight: '40px',
  },
  footer: { display: 'block' },
  form: { display: 'block', marginTop: '0em' },
  h1: {
    display: 'block',
    fontSize: '2em',
    marginTop: '0.67em',
    marginBottom: '0.67em',
    marginLeft: '0',
    marginRight: '0',
    fontWeight: 'bold',
  },
  h2: {
    display: 'block',
    fontSize: '1.5em',
    marginTop: '0.83em',
    marginBottom: '0.83em',
    marginLeft: '0',
    marginRight: '0',
    fontWeight: 'bold',
  },
  h3: {
    display: 'block',
    fontSize: '1.17em',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '0',
    marginRight: '0',
    fontWeight: 'bold',
  },
  h4: {
    display: 'block',
    marginTop: '1.33em',
    marginBottom: '1.33em',
    marginLeft: '0',
    marginRight: '0',
    fontWeight: 'bold',
  },
  h5: {
    display: 'block',
    fontSize: '.83em',
    marginTop: '1.67em',
    marginBottom: '1.67em',
    marginLeft: '0',
    marginRight: '0',
    fontWeight: 'bold',
  },
  h6: {
    display: 'block',
    fontSize: '.67em',
    marginTop: '2.33em',
    marginBottom: '2.33em',
    marginLeft: '0',
    marginRight: '0',
    fontWeight: 'bold',
  },
  head: { display: 'none' },
  header: { display: 'block' },
  hr: {
    display: 'block',
    marginTop: '0.5em',
    marginBottom: '0.5em',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderStyle: 'inset',
    borderWidth: '1px',
  },
  html: { display: 'block' },
  'html:focus': { outline: 'none' },
  i: { fontStyle: 'italic' },
  'iframe:focus': { outline: 'none' },
  'iframe[seamless]': { display: 'block' },
  img: { display: 'inline-block' },
  input: {},
  ins: { textDecoration: 'underline' },
  kbd: { fontFamily: 'monospace' },
  label: { cursor: 'default' },
  legend: {
    display: 'block',
    paddingLeft: '2px',
    paddingRight: '2px',
    border: 'none',
  },
  li: { display: 'list-item' },
  link: { display: 'none' },
  main: {},
  map: { display: 'inline' },
  mark: {
    backgroundColor: 'yellow',
    color: 'black',
  },
  menu: {
    display: 'block',
    listStyleType: 'disc',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '0',
    marginRight: '0',
    paddingLeft: '40px',
  },
  menuitem: {},
  meta: {},
  meter: {},
  nav: { display: 'block' },
  noscript: {},
  'object:focus': { outline: 'none' },
  ol: {
    display: 'block',
    listStyleType: 'decimal',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '0',
    marginRight: '0',
    paddingLeft: '40px',
  },
  optgroup: {},
  option: {},
  output: { display: 'inline' },
  p: {
    display: 'block',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '0',
    marginRight: '0',
  },
  param: { display: 'none' },
  picture: {},
  pre: {
    display: 'block',
    fontFamily: 'monospace',
    whiteSpace: 'pre',
    margin: '1em 0',
  },
  progress: {},
  q: { display: 'inline' },
  'q::before': { content: 'open-quote' },
  'q::after': { content: 'close-quote' },
  rp: {},
  rt: { lineHeight: 'normal' },
  ruby: {},
  s: { textDecoration: 'line-through' },
  samp: { fontFamily: 'monospace' },
  script: { display: 'none' },
  section: { display: 'block' },
  select: {},
  small: { fontSize: 'smaller' },
  span: { display: 'inline' },
  strike: { textDecoration: 'line-through' },
  strong: { fontWeight: 'bold' },
  style: { display: 'none' },
  sub: { verticalAlign: 'sub', fontSize: 'smaller' },
  sup: { verticalAlign: 'super', fontSize: 'smaller' },
  table: {
    display: 'table',
    borderCollapse: 'separate',
    borderSpacing: '2px',
    borderColor: 'gray',
  },
  tbody: {
    display: 'table-row-group',
    verticalAlign: 'middle',
    borderColor: 'inherit',
  },
  td: {
    display: 'table-cell',
    verticalAlign: 'inherit',
  },
  template: {},
  textarea: {},
  tfoot: {
    display: 'table-footer-group',
    verticalAlign: 'middle',
    borderColor: 'inherit',
  },
  th: {
    display: 'table-cell',
    verticalAlign: 'inherit',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  thead: {
    display: 'table-header-group',
    verticalAlign: 'middle',
    borderColor: 'inherit',
  },
  time: {},
  title: { display: 'none' },
  tr: {
    display: 'table-row',
    verticalAlign: 'inherit',
    borderColor: 'inherit',
  },
  track: {},
  u: { textDecoration: 'underline' },
  ul: {
    display: 'block',
    listStyleType: 'disc',
    marginTop: '1em',
    marginBottom: '1em',
    marginLeft: '0',
    marginRight: '0',
    paddingLeft: '40px',
  },
  var: { fontStyle: 'italic' },
  video: {},
  wbr: {},
}
