/// <reference path="../types.d.ts" />
import React, { useCallback, useContext, useState } from 'react'
import { nameForLocale } from '@/utils/name-for-locale'
import { flagForLocale } from '@/utils/flag-for-locale'
import { GlossaryEntriesShowContext } from '.'
import { useRequestWithNextRedirect } from './useRequestWithNextRedirect'

export function Unchecked({ translation }: { translation: GlossaryEntry }) {
  const { links } = useContext(GlossaryEntriesShowContext)
  const { sendRequestWithRedirect } = useRequestWithNextRedirect()
  const [editMode, setEditMode] = useState(false)
  const [copy, setCopy] = useState(translation.translation)
  const [textEditorValue, setTextEditorValue] = useState(
    translation.translation
  )
  const hasBeenEdited = copy !== translation.translation

  const updateCopy = useCallback(() => {
    if (textEditorValue !== copy) {
      setCopy(textEditorValue)
    }
    setEditMode(false)
  }, [textEditorValue, copy])

  const createProposal = useCallback(async () => {
    await sendRequestWithRedirect({
      method: 'POST',
      endpoint: links.createProposal.replace(
        'GLOSSARY_ENTRY_ID',
        translation.uuid
      ),
      body: JSON.stringify({ translation: copy }),
    })
  }, [sendRequestWithRedirect, links.createProposal, translation.uuid, copy])

  const cancelEditing = useCallback(() => {
    setTextEditorValue(copy)
    setEditMode(false)
  }, [copy])

  const resetChanges = useCallback(() => {
    setCopy(translation.translation)
    setTextEditorValue(translation.translation)
  }, [])

  return (
    <div className="locale unchecked">
      <div className="header">
        <div className="text-h4">
          {nameForLocale(translation.locale)} ({translation.locale})
        </div>
        <div className="status">Needs Checking</div>

        <div className="flag">{flagForLocale(translation.locale)}</div>
      </div>
      <div className="body">
        <p className="text-16 leading-140 mb-10">
          This is the locale version of the English text on the right. It was
          generated by an LLM. Please compare it to the original and check it
          for weirdnesses or inaccuracies then either edit it or approve it.
        </p>

        {editMode ? (
          <textarea
            className="mb-12 w-full p-16"
            rows={1}
            value={textEditorValue}
            onChange={(e) => setTextEditorValue(e.target.value)}
          />
        ) : (
          <div className="locale-value mb-12">{copy}</div>
        )}

        {editMode ? (
          <div
            className="buttons flex gap-8"
            style={{ justifyContent: 'flex-start' }}
          >
            <button onClick={cancelEditing} className="btn-s btn-default">
              Cancel
            </button>
            <button onClick={updateCopy} className="btn-s btn-default">
              Update
            </button>
          </div>
        ) : (
          <div className="buttons flex justify-between">
            <div className="buttons flex gap-8">
              <button
                onClick={() => setEditMode(true)}
                className="btn-s btn-default"
              >
                Edit Translation
              </button>
              {hasBeenEdited && (
                <button onClick={resetChanges} className="btn-s btn-default">
                  Reset changes
                </button>
              )}
            </div>
            <button onClick={createProposal} className="btn-s btn-primary">
              Submit proposal
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
