linters:
  InlineStyles:
    enabled: false

  LineLength:
    enabled: false

  ViewLength:
    enabled: false

  ConsecutiveSilentScripts:
    enabled: false

  ClassesBeforeIds:
    EnforcedStyle: id

  RuboCop:
    ignored_cops:
      # Defaults
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Layout/AlignHash # renamed to Layout/HashAlignment in rubocop 0.77
      - Layout/AlignParameters # renamed to Layout/ParameterAlignment in rubocop 0.77
      - Layout/CaseIndentation
      - Layout/ElseAlignment
      - Layout/EndOfLine
      - Layout/HashAlignment
      - Layout/IndentationWidth
      - Layout/LineLength # renamed from Metrics/LineLength in rubocop 0.79.0
      - Layout/ParameterAlignment
      - Layout/TrailingBlankLines # renamed to Layout/TrailingEmptyLines in rubocop 0.77
      - Layout/TrailingEmptyLines
      - Layout/TrailingWhitespace
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Metrics/LineLength
      - Naming/FileName
      - Naming/VariableNumber
      - Style/AsciiComments
      - Style/ConditionalAssignment
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier
      - Style/CaseLikeIf
      - Layout/EmptyLineAfterGuardClause
