require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: disable
  Exclude:
    - "app/controllers/tmp/**/*"
    - "bin/**/*"
    - "bin/{bundle,monitor-manifest,rails,rake,setup,yarn}"
    - "db/schema.rb"
    - "db/migrate/*"
    - "db/seeds.rb"
    - "node_modules/**/*"
    - "lib/solargraph-rails.rb"
    - "scripts/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/LineLength:
  Max: 135
  AutoCorrect: true
  Exclude:
    - "config/**/*"
    - "test/models/notifications/*"
    - "test/helpers/react_components/maintaining/submissions_summary_table_test.rb"

Lint/SuppressedException:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  # We probably want to bring this down but let's start here for now
  Max: 20
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/commands/solution/search_user_solutions_test.rb"
    - "test/serializers/serialize_submission_test_run_test.rb"

Naming/PredicateName:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  SingleLineConditionsOnly: false
  IncludeTernaryExpressions: false

Style/FormatString:
  EnforcedStyle: percent
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

# I don't mind this being enabled if
# someone fixes all the fails.
Style/ClassAndModuleChildren:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - "strip_h1"
    - "v2"

Style/LambdaCall:
  EnforcedStyle: braces

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Exclude:
    - "app/models/exercise/representation.rb"
    - "app/models/submission/representation.rb"

Rails/FilePath:
  EnforcedStyle: arguments

Rails/Blank:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/RefuteMethods:
  EnforcedStyle: refute

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HelperInstanceVariable:
  Exclude:
    - "app/helpers/view_components/**/*"
    - "app/helpers/react_components/**/*"
