export { highlightAll, useHighlighting, highlightAllAlways } from './highlight'
export { sendRequest } from './send-request'
export { pluralizeWithNumber } from './pluralizeWithNumber'
export { fromNow } from './date'
export { shortFromNow } from './time'
export { handleNavbarFocus } from './navbar-focus-handler'
export { scrollIntoView } from './scroll-into-view'
export { redirectTo } from './redirect-to'
export { typecheck } from './typecheck'
export { showSiteFooterOnTurboLoad } from './show-site-footer'
export { makeTablesResponsive } from './make-tables-responsive'
