# Retrieves a concept's parsed about and introduction documents from S3,
# falling back to generating them live on a miss (and lazily filling the
# cache off the request path). Any S3 failure also falls back to live
# generation, so this can never raise to the user because of the cache.
#
# Keys are versioned with synced_to_git_sha, so there is nothing to
# invalidate: a sync moves the concept onto a new key. Unlike an
# exercise, a concept has no sha of its own and reads its documents at
# the repository's HEAD, so this key turns over on every track sync
# rather than only when the concept's own content changes. That costs a
# regeneration per concept per sync, which is negligible against the
# reads it saves in between.
#
# The uuid is sharded into the key to avoid hot S3 prefixes (uuids are
# compact hex, so their leading characters are uniformly distributed).
class Concept::CachedContent::Retrieve
  include Mandate

  initialize_with :concept

  def call
    cached || generate!
  end

  private
  def cached = S3Cache::Read.(cache_key)

  # The content built here is handed straight to the deferred write rather
  # than being regenerated by it, which would parse the documents twice.
  #
  # The key is captured here too, not recomputed in the job. It is derived
  # from synced_to_git_sha, and the job reloads the concept through a
  # GlobalID, so a sync landing in between would file this content under
  # the new sha's key, where it would be read back as that sync's content.
  def generate!
    Concept::CachedContent::Generate.(concept).tap do |content|
      S3Cache::Write.defer(cache_key, content)
    end
  end

  def cache_key
    uuid = concept.uuid
    "concept-content/#{uuid[0, 2]}/#{uuid[2, 2]}/#{uuid}/#{concept.synced_to_git_sha}.json"
  end
end
