# Retrieves the cached solution-view payload from S3, falling back to
# generating it live on a miss (and lazily filling the cache off the
# request path). Any S3 failure also falls back to live generation, so
# this can never raise to the user because of the cache.
#
# Keys are versioned with updated_at, so a stale entry is simply never
# read again after the solution changes. The uuid is sharded into the
# key to avoid hot S3 prefixes (uuids are compact hex, so their leading
# characters are uniformly distributed).
class Solution::CachedSerializedView::Retrieve
  include Mandate

  initialize_with :solution

  def call
    cached || generate!
  end

  private
  def cached = S3Cache::Read.(cache_key)

  # The payload built here is handed straight to the deferred write
  # rather than being regenerated by it: a miss otherwise serializes the
  # solution twice, and misses are the common case while the cache fills.
  #
  # The key is captured here too, not recomputed in the job. It is derived
  # from updated_at, and the job reloads the solution through a GlobalID —
  # so a solution that changes between request and job would file this
  # (now old) payload under the new version's key, where it would be read
  # back as current. Capturing both together keeps them the same version.
  def generate!
    Solution::CachedSerializedView::Generate.(solution).tap do |payload|
      S3Cache::Write.defer(cache_key, payload)
    end
  end

  def cache_key
    uuid = solution.uuid
    "solution-view/#{uuid[0, 2]}/#{uuid[2, 2]}/#{uuid}/#{solution.updated_at.to_i}.json"
  end
end
