import React from 'react'

export function ProposalDescription({ locale }: { locale: string }) {
  return (
    <p className="text-16 leading-140 mb-10">
      <>
        This is the <span>{locale}</span> version of the English text on the
        right. It was generated by an LLM and reviewed by another translator who
        has marked it as correct.
      </>{' '}
      Please compare it to the original and either approve it, reject it, or
      edit it further.
    </p>
  )
}
