en:
  site_updates:
    new_exercise:
      1: >
        <em>%{maker_handles}</em> published a new Exercise: <a href="%{exercise_url}">%{exercise_title}</a>

    new_concept:
      1: >
        <em>%{maker_handles}</em> published a new Concept: <a href="%{concept_url}">%{concept_name}</a>

    arbitrary:
      1: >
        <em>%{author_handle}</em> published a new update.
