en:
  courses:
    scrolling_testimonials:
      testimonials:
        challenge_fun: “Perfect mixture of challenge and fun”
        amazing_value: “Amazing value”
        best_time_investment: “My best time investment for years”
        incredibly_fun: “Incredibly Fun!”
        transformative: “Its been transformative!”
        will_learn_code: “You *will* learn to code”
        learning_as_should_be: “Learning, as it should be!”
        best_course_done: “The best course I've done”
        made_learning_joy: “Made learning a joy again”
        bootcamp_pure_gold: “This bootcamp is pure gold.”
        wonderful_learning_experience: “A wonderful Learning Experience”
        proper_hands_on_learning: “Proper Hands-on learning”
        knowledge_didnt_think_needed: “The knowledge you didn't think you needed”
        recommended: “100% recommended!”
        so_glad_stumbled: “So glad I stumbled on this”
        great_way_learn: “A great way to learn!”
        fun_exercises_clear_explanations_cool_hats: “Fun exercises, clear explanations, cool hats”
        exceptional_course_outstanding: “Exceptional course, truly outstanding”
        addictive_good_way: “Addictive in a good way”
        amazing_fun: “Amazing fun”
        fantastic_community: “Fantastic community”
        zero_coding_experience_required: “Zero coding experience required”
        fun_inspiring: “Fun and inspiring”
        changed_way_think: “It's changed the way I think about learning”
        rewarding_journey: “An incredibly rewarding journey”
        insane_value: “Insane value”
        opportunity_learn_master: “An opportunity to learn from a bonafide master”
        amazing_lovely_thing: “It's really an amazing and lovely thing”
        best_investment: “The best investment I made in myself this year”
        increased_confidence_motivation: “Its massively increased my confidence and motivation”
        supportive_community: “Very supportive community!”
        even_prior_programmer_transformative: “Even as a prior programmer, its transformative!”
