en:
  courses:
    enrolled:
      bundle_coding_front_end:
        welcome_message: We're so excited to have you on board! 💙
        logged_in_access_html:
          <strong>Your Exercism account has been granted access to
          the Bootcamp.</strong> Please use the button below to get started.
        email_welcome_html:
          You should shortly receive an email welcoming you and asking
          you to say hello. <strong>Please do reply</strong> and tell us your
          story - it's both incredibly motivating for us to hear about who's
          taking our courses, and also means we can better tailor what we're
          making!
        support_email_html:
          If you have any questions, please email us at <strong><span
          class="font-medium">%{email}</span></strong> and we'll be happy to
          help.
        go_to_bootcamp: Go to the Bootcamp
        not_logged_in_access_html:
          "<strong>As you're not logged into your Exercism
          account, we need to connect things up for you.</strong> Firstly,
          please make sure you have an Exercism account:"
        login_if_account_exists: If you do, logging in should give you access.
        create_account_instructions_html:
          If you don't, the easiest way to get access is
          to %{sign_up_link} with the email address "%{email}". If you use a
          different email and don't get access, please email us at <strong><span
          class="font-medium">bootcamp@exercism.org</span></strong> with your
          Exercism username/handle and the email address you've enrolled with
          (%{email}) and we'll give you access manually.
        email_welcome_not_logged_in_html:
          You should also shortly receive an email
          welcoming you, and asking you to say hello. <strong>Please do
          reply</strong> and tell us your story - it's both incredibly
          motivating for us to hear about who's joining the Bootcamp, and also
          means we can better tailor what we're making!
        thanks_for_trusting: Thanks for trusting us with your learning 🙂
