import React from 'react'
import { flagForLocale } from '@/utils/flag-for-locale'

export function Unchecked({ translation }: { translation: Translation }) {
  return (
    <div className="locale unchecked">
      <div className="header">
        {/* TODO GET LOCALE NAME */}
        <div className="text-h4">Locale Name ({translation.locale})</div>
        <div className="status">Needs Checking</div>

        <div className="flag">{flagForLocale(translation.locale)}</div>
      </div>
      <div className="body">
        <p className="text-16 leading-140 mb-10">
          This is the locale version of the English text on the right. It was
          generated by an LLM. Please compare it to the original and check it
          for weirdnesses or inaccuracies then either edit it or approve it.
        </p>
        <div className="locale-value mb-12">{translation.value}</div>
        <div className="buttons flex gap-8">
          <button className="btn-s btn-default">Edit LLM Translation</button>
          <button className="btn-s btn-default">Approve Translation</button>
        </div>
      </div>
    </div>
  )
}
