class Track::Trophies::Shared::CompletedFiveDifficultExercisesTrophy < Track::Trophy
  # Generated by: Exercise.joins(:track).where('difficulty >= 8').distinct.pluck('tracks.slug')
  self.valid_track_slugs = %w[
    8th awk babashka bash c ceylon chapel clojure clojurescript cpp csharp d dart
    delphi elixir elm erlang fortran fsharp gleam go haskell java javascript
    jq julia kotlin lua nim ocaml python red ruby rust scala scheme swift tcl
    typescript unison vbnet vlang wasm
  ]

  def name(_) = "Difficult"
  def icon = 'trophy-completed-five-difficult-exercises'

  def criteria(track)
    "Awarded once you complete %<num_exercises>i difficult exercises in %<track_title>s" % {
      num_exercises: NUM_EXERCISES,
      track_title: track
    }
  end

  def success_message(track)
    "Congratulations on completing %<num_exercises>i difficult exercises in %<track_title>s" % {
      num_exercises: NUM_EXERCISES,
      track_title: track
    }
  end

  def award?(user_track) = user_track.completed?

  NUM_EXERCISES = 5
  private_constant :NUM_EXERCISES
end
