en:
  community:
    brief_introductions:
      index:
        title: The Brief Introduction Series
        description_one:
          Explore new languages with our "Brief Introduction" series.
          Join Erik as he looks at the history, and fundamentals of a language,
          and solves an exercise in it.
        description_two:
          Check out his latest video to the right, or explore the full
          series below.
