# frozen_string_literal: true

require "json"

# Input directory with your per-file TS translations
DIR = Rails.root.join("app/javascript/i18n/en")

# Output single TS file - the unified javascript-copy.ts
OUTPUT_TS = Rails.root.join("i18n/javascript-copy.ts")

# If you prefer to split by namespace (per file), set this to true.
# When true, each filename (without .ts) becomes a namespace under `en`.
# When false, everything goes into the "translation" namespace.
GROUP_BY_FILENAME_AS_NAMESPACE = false

# Matches JavaScript object keys: unquoted identifiers or quoted strings
PAIR_REGEX = /
  (?<key>
    [a-zA-Z_][a-zA-Z0-9_]*      # unquoted identifier (selectedTracks_one)
    |
    ['"][^'"]*['"]              # quoted key ('trackCheckbox.trackSelected')
  )
  \s*:\s*
  (?<val>
    "(?:[^"\\]|\\.)*"           # double-quoted string value
    |
    '(?:[^'\\]|\\.)*'           # single-quoted string value
  )
/x

# Collect all translations here
# Either: { "translation" => { "k" => "v" } }
# Or:     { "fileA" => { ... }, "fileB" => { ... } }
AGGREGATED = Hash.new { |h, k| h[k] = {} }

def import_file(file_path)
  puts "📂 Importing #{file_path}"
  content = File.read(file_path)

  namespace =
    if GROUP_BY_FILENAME_AS_NAMESPACE
      File.basename(file_path, ".ts")
    else
      "translation"
    end

  content.scan(PAIR_REGEX) do |key, raw_val|
    # Strip quotes from key if it's quoted
    key = key[1..-2] if key.start_with?('"', "'")
    
    # Strip quotes from value
    value = raw_val[1..-2] # strip surrounding quotes
    value = value.gsub("\\'", "'").gsub('\\"', '"')

    # Save into DB (kept from your original script)
    begin
      Localization::Original::Create.(:website_client_side, key, value, nil, false)
    rescue ActiveRecord::RecordNotUnique
      # Skip duplicates quietly
    rescue ActiveRecord::RecordInvalid => e
      puts "⚠️ Failed to import #{key}: #{e.message}"
    end

    # Aggregate for TS output
    AGGREGATED[namespace][key] = value
  end
end

Dir.glob(DIR.join("*.ts")).each { |file| import_file(file) }

# Build the TypeScript module contents
# Shape matches i18next's `resources` option:
# { en: { translation: { ... } } } or { en: { ns1: {...}, ns2: {...} } }
resources_payload = { "en" => AGGREGATED }

# Serialize to JSON (safe escaping), then wrap as TypeScript
json = JSON.pretty_generate(resources_payload)
ts = <<~TS
  /* Auto-generated by script: #{File.basename(__FILE__)} */
  /* Do not edit by hand. */
  export const resources = #{json} as const;
  export default resources;
TS

File.write(OUTPUT_TS, ts)
puts "✅ Wrote aggregated resources to: #{OUTPUT_TS}"