export { useReadonlyCompartment } from './useReadonlyCompartment'
export { useHighlightLine } from './useHighlightLine'
export { useHighlightLineColor } from './useHighlightLineColor'
export { useUnderlineRange } from './useUnderlineRange'
export { useReadonlyRanges } from './useReadonlyRanges'
