name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  code-coverage:
    if: github.repository == 'exercism/website'

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: exercism
          MYSQL_PASSWORD: exercism
          MYSQL_DATABASE: exercism_test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 1s
          --health-timeout 2s
          --health-retries 10

      aws:
        image: "localstack/localstack:0.12.3"
        ports:
          - 4566

      opensearch:
        image: opensearchproject/opensearch:1.1.0
        env:
          discovery.type: single-node
        ports:
          - 9200

    steps:
      ###
      # Checkout using GitHub's checkout action
      - uses: actions/checkout@v2

      ###
      # Setup Ruby - this needs to match the version in the Gemfile
      - name: Set up Ruby
        uses: ruby/setup-ruby@a699edbce608a2c128dedad88e3b6a0e28687b3c
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      ###
      # Caching using GitHub's caching action

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      ###
      # Install bundler and yarn dependencies
      - name: Install dependencies
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true
          AWS_PORT: ${{ job.services.aws.ports['4566'] }}
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: |
          yarn install
          bundle exec setup_exercism_config
          bundle exec setup_exercism_local_aws

      ###
      # Setup code climate
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      ###
      # Precompile JS
      - name: Precompile JS
        env:
          RAILS_ENV: test
          EXERCISM_CI: true
        run: |
          ./bin/webpack
      ###
      # Run the tests
      - name: Build Code Coverage
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true
          AWS_PORT: ${{ job.services.aws.ports['4566'] }}
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
          OPENSEARCH_PORT: ${{ job.services.opensearch.ports['9200'] }}
          OPENSEARCH_HOST: https://127.0.0.1:${{ job.services.opensearch.ports['9200'] }}
          OPENSEARCH_VERIFY_SSL: false
          CAPTURE_CODE_COVERAGE: true
        run: |
          bundle exec rails test:zeitwerk

          bundle exec rails test
          ./cc-test-reporter format-coverage -t simplecov -o codeclimate.backend.json coverage/backend/.resultset.json

          bundle exec rails test:system
          ./cc-test-reporter format-coverage -t simplecov -o codeclimate.system.json coverage/backend/.resultset.json

      ###
      # Publish the coverage to CodeClimate
      - name: Publish code coverage
        #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          GIT_BRANCH: ${GITHUB_REF/refs\/heads\//}
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        run: |
          ./cc-test-reporter sum-coverage codeclimate.*.json -p 2 -o codeclimate.total.json
          ./cc-test-reporter upload-coverage -i codeclimate.total.json
