name: Tests

on:
  push:
    branches: [main]
  pull_request:

# Cancel superseded runs on PRs so they don't compete for runners
concurrency:
  group: tests-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ##################
  ##### RUBOCOP ####
  ##################
  rubocop:
    if: github.repository == 'exercism/website'

    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Set up Ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb
        with:
          ruby-version: .ruby-version

      - name: Install gems
        run: |
          # Extract the exact versions of the rubocop gems from Gemfile.lock
          rubocop_version=$(sed -n -E 's/^    rubocop \((.+)\)/\1/p' Gemfile.lock)
          rubocop_minitest_version=$(sed -n -E 's/^    rubocop-minitest \((.+)\)/\1/p' Gemfile.lock)
          rubocop_performance_version=$(sed -n -E 's/^    rubocop-performance \((.+)\)/\1/p' Gemfile.lock)
          rubocop_rails_version=$(sed -n -E 's/^    rubocop-rails \((.+)\)/\1/p' Gemfile.lock)
          activesupport_version=$(sed -n -E 's/^    activesupport \((.+)\)/\1/p' Gemfile.lock)

          gem install activesupport -v $activesupport_version
          gem install rubocop -v $rubocop_version
          gem install rubocop-minitest -v $rubocop_minitest_version
          gem install rubocop-performance -v $rubocop_performance_version
          gem install rubocop-rails -v $rubocop_rails_version

      - name: Run Rubocop
        run: rubocop --except Metrics

  ###################
  ##### JS TESTS ####
  ###################
  js-tests:
    if: github.repository == 'exercism/website'

    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      ###
      # Checkout using GitHub's checkout action
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      ###

      # Caching using GitHub's caching action
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      ###
      # Install yarn dependencies
      - name: Install dependencies
        run: yarn install

      ###
      # Run the tests
      - name: Run JS tests
        run: yarn test

  #####################
  ##### RUBY TESTS ####
  #####################
  ruby-test-files:
    if: github.repository == 'exercism/website'

    runs-on: ubuntu-22.04
    timeout-minutes: 30
    outputs:
      matrix: ${{ steps.test-files.outputs.matrix }}

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - id: test-files
        env:
          BATCHES: 11
        run: |
          echo "matrix=$(ruby .github/scripts/split-tests.rb ${{ env.BATCHES }} .github/test-timings.json $(find test -name '*_test.rb' -not -path 'test/system/*' -not -path 'test/visual/*'))" >> $GITHUB_OUTPUT

  ruby-tests:
    if: github.repository == 'exercism/website'

    needs:
      - ruby-test-files
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.ruby-test-files.outputs.matrix) }}

    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Start services
        run: .github/scripts/start-services.sh

      - name: Set up Ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@7ca5f46d061ad9aa95863cd9b214dd48edef361d
        with:
          packages: graphicsmagick libvips
          version: 1.0

      - name: Prepare assets
        uses: ./.github/actions/prepare-assets

      - name: Wait for services
        run: .github/scripts/wait-for-services.sh

      - name: Setup Exercism services
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true
          AWS_PORT: 4566
          MYSQL_PORT: 3306
        run: |
          bundle exec setup_exercism_config
          bundle exec setup_exercism_local_aws

      ###
      # Run the tests
      - name: Run Ruby tests
        env:
          RAILS_ENV: test
          EXERCISM_CI: true
          AWS_PORT: 4566
          MYSQL_PORT: 3306
          OPENSEARCH_PORT: 9200
          OPENSEARCH_HOST: https://127.0.0.1:9200
          OPENSEARCH_VERIFY_SSL: false
          SKIP_JS_BUILD: true
          SKIP_CSS_BUILD: true
          TEST_TIMINGS_FILE: test-timings.json

        run: |
          bundle exec rails test:prepare test:zeitwerk
          bundle exec rails test ${{ matrix.tests }}

      - name: Upload test timings
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: test-timings-${{ strategy.job-index }}-ruby
          path: test-timings.json
          if-no-files-found: ignore

  ruby-tests-completed:
    runs-on: ubuntu-22.04
    needs: ruby-tests
    steps:
      - run: echo "Ruby tests completed"

  #######################
  ##### SYSTEM TESTS ####
  #######################
  system-test-files:
    if: github.repository == 'exercism/website'

    runs-on: ubuntu-22.04
    timeout-minutes: 30
    outputs:
      matrix: ${{ steps.test-files.outputs.matrix }}

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - id: test-files
        env:
          BATCHES: 10
        run: |
          echo "matrix=$(ruby .github/scripts/split-tests.rb ${{ env.BATCHES }} .github/test-timings.json $(find test/system -name '*_test.rb'))" >> $GITHUB_OUTPUT

  system-tests:
    if: github.repository == 'exercism/website'

    needs:
      - system-test-files

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.system-test-files.outputs.matrix) }}

    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      ###
      # Checkout using GitHub's checkout action
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Start services
        run: .github/scripts/start-services.sh

      ###
      # Setup Ruby - this needs to match the version in the Gemfile
      - name: Set up Ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@7ca5f46d061ad9aa95863cd9b214dd48edef361d
        with:
          packages: libvips
          version: 1.0

      - name: Prepare assets
        uses: ./.github/actions/prepare-assets

      - name: Wait for services
        run: .github/scripts/wait-for-services.sh

      - name: Setup Exercism services
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true
          AWS_PORT: 4566
          MYSQL_PORT: 3306
        run: |
          bundle exec setup_exercism_config
          bundle exec setup_exercism_local_aws

      ###
      # Run the tests
      - name: Run Ruby system tests
        env:
          RAILS_ENV: test
          EXERCISM_CI: true
          AWS_PORT: 4566
          MYSQL_PORT: 3306
          OPENSEARCH_PORT: 9200
          OPENSEARCH_HOST: https://127.0.0.1:9200
          OPENSEARCH_VERIFY_SSL: false
          SKIP_JS_BUILD: true
          SKIP_CSS_BUILD: true
          TEST_TIMINGS_FILE: test-timings.json
        run: |
          bundle exec rails test:prepare
          bundle exec rails test ${{ matrix.tests }}

      - name: Upload test timings
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: test-timings-${{ strategy.job-index }}-system
          path: test-timings.json
          if-no-files-found: ignore

  system-tests-completed:
    runs-on: ubuntu-22.04
    needs: system-tests
    steps:
      - run: echo "System tests completed"

  ######################
  ##### ASSET TESTS ####
  ######################
  asset-tests:
    if: github.repository == 'exercism/website'

    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      ###
      # Checkout using GitHub's checkout action
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      ###
      # Setup Ruby - this needs to match the version in the Gemfile
      - name: Set up Ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      ###
      # Caching using GitHub's caching action

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      ###
      # Install bundler and yarn dependencies
      - name: Install dependencies
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true
          AWS_PORT: 4566
          MYSQL_PORT: 3306
          OPENSEARCH_PORT: 9200
        run: |
          yarn install

      - name: Run asset tests
        env:
          RAILS_ENV: test
          EXERCISM_CI: true
        run: |
          bundle exec rails r bin/monitor-manifest
          bundle exec rails test:prepare
